# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.13"]

    steps:
      - uses: actions/checkout@v3
    #   - uses: chartboost/ruff-action@v1 # Fail fast if there are any linting errors
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      # - name: Static type check
        # run: make typecheck
      - name: Test with pytest
        run: |
          uv run make test
      # - name: Test docstrings with pytest
        # run: |
          # uv run make doctest
